name: Actions Workflow Name 001

on:
  schedule:
    - cron: '0 3 * jan *'
  release:
    types: [published]
  push:
    branches:
      - main
    paths:
      # - '/Dockerfile'
      - '.github/workflows/test001.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TARGET_IMAGE_NAME: ${{ vars.IMAGE_NAME }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create Tag for Confirmation
    #  id: vars
    # schedule push / use TIMESTAMP as tag
    # workflow_dispatch / use Action variable as tag
    # release / use github.ref_name (tag) as tag
    # if you need to pass variables between steps, use $GITHUB_ENV
      run: |
        TIMESTAMP=$(date +'%Y%m%d%H%M%S')
        TAG=$TIMESTAMP
        if [ "${{ github.event_name }}" = "release" ]; then
          TAG="${{ github.ref_name }}"
        fi
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          TAG="${{ vars.DOCKER_USERNAME }}"
        fi
        echo "TAG=$TAG" >> $GITHUB_ENV
        echo "$TAG"

    - name : Diplay github contexts
      run: |
        echo "$TIMESTAMP"
        # timestamp is empty because it is not defined in this run
        echo "$TAG"
        GITHUB_API_URL="${{ github.api_url }}"
        GITHUB_BASE_REF="${{ github.base_ref }}"
        GITHUB_ENV="${{ github.env }}"
        GITHUB_EVENT="${{ github.event }}"
        GITHUB_EVENT_NAME="${{ github.event_name }}"
        GITHUB_EVENT_PATH="${{ github.event_path }}"
        GITHUB_HEAD_REF="${{ github.head_ref }}"
        GITHUB_JOB="${{ github.job }}"
        GITHUB_PATH="${{ github.path }}"
        GITHUB_REF="${{ github.ref }}"
        GITHUB_REF_NAME="${{ github.ref_name }}"
        GITHUB_REF_PROTECTED="${{ github.ref_protected }}"
        GITHUB_REF_TYPE="${{ github.ref_type }}"
        GITHUB_REPOSITORY="${{ github.repository }}"
        GITHUB_REPOSITORY_ID="${{ github.repository_id }}"
        GITHUB_REPOSITORY_URL="${{ github.repositoryUrl }}"
        GITHUB_TRIGGERING_ACTOR="${{ github.triggering_actor }}"
        GITHUB_WORKFLOW="${{ github.workflow }}"
        GITHUB_WORKFLOW_REF="${{ github.workflow_ref }}"
        GITHUB_WORKSPACE="${{ github.workspace }}"
        echo "Using tag: ${{ env.TAG }}"
        echo "Using docker_username: ${{ vars.DOCKER_USERNAME }}"
        echo "Using docker_access_token: ${{ secrets.DOCKER_ACCESS_TOKEN }}"


