name: Auto Push to Dev

on:
  push:
    branches:
      - dev
    paths:
      - '/Dockerfile'
      - '.github/workflows/auto-push-dev.yml'
  schedule:
    - cron: '0 2 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DEV_IMAGE_NAME: stellarhub/dev-target

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Build Tag
      id: vars
      run: |
        TIMESTAMP=$(date +'%Y%m%d%H%M%S')
        TAG="${{ github.event.inputs.tag }}"
        if [ -z "$TAG" ]; then
          TAG=$TIMESTAMP
        fi
        echo "TAG=$TAG" >> $GITHUB_ENV

    - name: Display Tag for Confirmation
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        echo "Using tag: $TAG"

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker buildx create --name mybuilder --use
        docker buildx inspect --bootstrap

    - name: Build and push Docker image for multiple architectures
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 -t ${{ env.DEV_IMAGE_NAME }}:${{ env.TAG }} --push .

    - name: Get image digest
      id: get_digest
      run: |
        DIGEST=$(docker buildx imagetools inspect ${{ env.DEV_IMAGE_NAME }}:${{ env.TAG }} | grep -m 1 "Digest:" | awk '{ print $2 }')
        echo "DIGEST=$DIGEST" >> $GITHUB_ENV

    - name: Push Docker image with latest tag
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 -t ${{ env.DEV_IMAGE_NAME }}:latest --push .

    - name: Save Dockerfile and tag information to JSON
      run: |
        echo "{\"image_name\": \"${{ env.DEV_IMAGE_NAME }}\", \"tag\": \"${{ env.TAG }}\", \"digest\": \"${{ env.DIGEST }}\"}" > dev-build-info.json

    - name: Upload build info as artifact
      uses: actions/upload-artifact@v4
      with:
        name: dev-build-info
        path: dev-build-info.json

    - name: Log success to Google Sheets
      if: success()
      run: |
        JSON_PAYLOAD=$(echo '{"image_name": "${{ env.DEV_IMAGE_NAME }}", "tag": "${{ env.TAG }}", "digest": "${{ env.DIGEST }}", "status": "successful", "env": "dev"}')
        echo "Sending JSON payload: $JSON_PAYLOAD"
        curl -X POST -H "Content-Type: application/json" -d "$JSON_PAYLOAD" ${{ secrets.GOOGLE_SHEETS_WEB_APP_URL }}

    - name: Log failure to Google Sheets
      if: failure()
      run: |
        JSON_PAYLOAD=$(echo '{"image_name": "${{ env.DEV_IMAGE_NAME }}", "tag": "${{ env.TAG }}", "digest": "${{ env.DIGEST }}", "status": "failed", "env": "dev"}')
        echo "Sending JSON payload: $JSON_PAYLOAD"
        curl -X POST -H "Content-Type: application/json" -d "$JSON_PAYLOAD" ${{ secrets.GOOGLE_SHEETS_WEB_APP_URL }}
