name: variables 001

on:
  push:
    branches:
      - main
    paths:
      - '/Dockerfilex'
      - '.github/workflows/FileToWatch.yml'
  schedule:
    - cron: '0/21 2-5,8 31 1-mar 1-2,fri-sat'
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ vars.IMAGE_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Examine variables
        run: |
          DOCKERFILE_VER=$(grep -m 1 '^ARG VERSION=' Dockerfile | cut -d '=' -f 2)
          echo "DOCKERFILE_VER=$DOCKERFILE_VER" >> $GITHUB_ENV   

          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          echo "TIMESTAMP=$TIMESTAMP" >> GITHUB_ENV

          TAG="${{ vars.TAG }}"
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Display variables for Confirmation
        run: |
          echo "TAG variable   : $TAG"
          echo "Dockerfile ARG : $VERSION"
          echo "Timestamp build: $TIMESTAMP"

      - name: Set up Docker Build Tag
        run: |
          VERSION=$(grep -m 1 '^ARG VERSION=' Dockerfile | cut -d '=' -f 2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

          if [ "${{ github.event_name }}" = "release" ]; then
            TAG="${{ github.ref_name }}"
          fi
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            TAG="${{ github.event.inputs.tag }}"
            if [ -z "$TAG" ]; then
              TAG="${{ vars.TAG }}"
            fi
          fi
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          echo "TIMESTAMP=$TIMESTAMP" >> GITHUB_ENV
          if [ -z "$TAG" ]; then
            TAG=$TIMESTAMP
          fi
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Display Tag for Confirmation
        run: |
          echo "TAG variable   : $TAG"
          echo "Dockerfile ARG : $VERSION"
          echo "Timestamp build: $TIMESTAMP"
          echo ${{ env.TAG }}

            