name: workflow name 004

on:
  push:
    branches:
      - main
    paths:
      - '/Dockerfilex'
      - '.github/workflows/FileToWatch.yml'
  schedule:
    - cron: '0/21 2-5,8 31 1-mar 1-2,fri-sat'
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ vars.IMAGE_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v5

      - name: Set up Docker Build Tag
        run: |
          VERSION=$(grep -m 1 'ARG VERSION=' Dockerfile | cut -d '=' -f 2)
          echo "VERSIONN=$VERSION" >> $GITHUB_ENV

          if [ "${{ github.event_name }}" = "release" ]; then
            TAG="${{ github.ref_name }}"
          fi
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            TAG="${{ github.event.inputs.tag }}"
            if [ -z "$TAG" ]; then
              TAG="${{ vars.TAG }}"
            fi
          fi
          if [ -z "$TAG" ]; then
            TIMESTAMP=$(date +'%Y%m%d%H%M%S')
            TAG=$TIMESTAMP
          fi
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Display Tag for Confirmation
        # if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "Using tag       : $TAG"
          echo "Using Dockerfile: $VERSION"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            $IMAGE_NAME:latest
            $IMAGE_NAME:$TAG
